### ISSUE TITLE
problem with bans and kicks and mutes 

### ISSUE THREAD

**Issue by iiiiii1wepfj** [TGExplore/Marie-2.0-English#21]
**Hello, there is a problem with the bot that every time a manager does not have permission to remove people from the group, it is enough that he has minimal management so the bot lets him do it as if he has the option to remove the people from the group**, can you fix the glitch?

**Comment by TGExplore** [comment]
What?
Not understand

**Comment by iiiiii1wepfj** [comment]
why admin with only pin message can use ban command in the bot?

**Comment by TGExplore** [comment]
Administrator can only ban members.
Bot not admin, can't do anything
